
# ===== FactionMobs Config =====

# Sets the model of the mobs. Can be 0 (skeleton), 1 (zombie) or 2 (pigzombie)
model: 2

# Sets the maximum number of Faction Mobs that can spawn 
# No monsters will naturally spawn if there are too many
spawnLimit: 60

# Attack naturally spawning hostile mobs
attackMobs: true

# Enable periodic saving in case of server crash
autoSave: false
# Minutes between each save
saveInterval: 10

# Prevent mobs from damaging friendly players and mobs
noFriendlyFire: true

# === Per Mob Config ===

# Allowed to spawn, disabling does not remove existing mobs
Archer.enabled: true
# Health
Archer.maxHp: 20
# Custom damage, set to 0 to use default damage (normal damage is about 2)
Archer.damage: 0
# Faction power spent upon spawning this mob
Archer.powerCost: 4.0
# Money spent upon spawning this mob, requires Vault
Archer.moneyCost: 0.0

Mage.enabled: true
Mage.maxHp: 20
# Mage damage not modifiable
Mage.powerCost: 6.0
Mage.moneyCost: 0.0

Swordsman.enabled: true
Swordsman.maxHp: 20
# Normal damage is about 5
Swordsman.damage: 0
Swordsman.powerCost: 5.0
Swordsman.moneyCost: 0.0

Titan.enabled: true
Titan.maxHp: 40
# Normal damage is about 15
Titan.damage: 0
Titan.powerCost: 11.0
Titan.moneyCost: 0.0

# === Experimental Config Options - edit at your own risk ===

# Set the normal movement speed of the mobs (Recommend between .3 and .5, default .3)
mobSpeed: .3

# Set the speed of the mobs when patroling (Recommend between .175 and .3, default .175)
mobPatrolSpeed: .175

# Set the distance the mobs will attempt to pathfind (Recommend between 16 and 128, default 64)
mobNavRange: 64