name: FactionMobs
main: com.gmail.scyntrus.fmob.FactionMobs
author: Scyntrus
version: 1.4_1.5B2663
depends: [Factions]
softdepends: [Vault]
commands:
    fm:
        description: spawn something
        usage: "/fm [spawn|color] [parameters]"
        aliases: fmob
permissions:
    fmob.spawn:
        description: Allows you to use /fm spawn
        default: op
    fmob.color:
        description: Allows you to use /fm color
        default: op
    fmob.order:
        description: Allows you to use /fm order
        default: op
    fmob.order.tp:
        description: Allows you to use /fm order [tpSpawn,tpHere]
        default: op
    