name: FactionMobs
main: com.gmail.scyntrus.fmob.FactionMobs
author: Scyntrus
version: 1.7_1.5.1
depends: [Factions]
softdepends: [Vault]
commands:
    fm:
        description: spawn something
        usage: "/fm [spawn|order|color] [parameters]"
        aliases: fmob
permissions:
    fmob.spawn:
        description: Allows you to use /fm spawn
        default: true
    fmob.color:
        description: Allows you to use /fm color
        default: true
    fmob.order:
        description: Allows you to use /fm order
        default: true
    fmob.order.move:
        description: Allows you to use /fm order moveToPoint
        default: true
    fmob.order.tp:
        description: Allows you to use /fm order [tpSpawn|tpHere]
        default: op
    fmob.bypass:
        description: Allows you to spawn mobs without restriction
        default: op
    