name: FactionMobs
main: com.gmail.scyntrus.fmob.FactionMobs
author: Scyntrus
version: ${version}_${craftbukkit.version}
softdepend: [Factions, Towny, SimpleClans, Kingdoms, Feudal, Vault, LibsDisguises, PremiumTurrets]
commands:
    fm:
        description: Faction mobs control
        usage: "/fm [spawn|order|color] [parameters]"
        aliases: [fmob, tm, tmob, mob]
    fmc:
        description: Spawn a unit for a specific faction. Designed to be used by command blocks
        usage: "/fmc TYPE FACTIONTAG WORLDNAME X Y Z [EXTRAINFO]"
        aliases: tmc
permissions:
    fmob.spawn:
        description: Allows you to use /fm spawn with all units
        default: true
    fmob.spawn.archer:
        description: Allows you to use /fm spawn archer
        default: false
    fmob.spawn.mage:
        description: Allows you to use /fm spawn mage
        default: false
    fmob.spawn.swordsman:
        description: Allows you to use /fm spawn swordsman
        default: false
    fmob.spawn.titan:
        description: Allows you to use /fm spawn titan
        default: false
    fmob.spawn.spiritbear:
        description: Allows you to use /fm spawn spiritbear
        default: false
    fmob.color:
        description: Allows you to use /fm color
        default: true
    fmob.order:
        description: Allows you to use /fm order
        default: true
    fmob.order.move:
        description: Allows you to use /fm order moveToPoint
        default: true
    fmob.order.tp:
        description: Allows you to use /fm order [tpHome|tpHere]
        default: op
    fmob.order.attackall:
        description: Allows you to use /fm order attackall
        default: true
    fmob.bypass:
        description: Allows you to spawn mobs without restriction
        default: false
    fmob.fmc:
        description: Allows you to use /fmc, a command designed for command blocks
        default: false
    fmob.selectall:
        description: Allows you to use /fm selectall
        default: op
    